name: otp_autofill
version: 2.1.0
description: Android implementation of OTP autofill with using User Consent API and Retriever API. Add possibility to receive OTP code from another input.
repository: "https://github.com/surfstudio/flutter-otp-autofill"
issue_tracker: "https://github.com/surfstudio/flutter-otp-autofill/issues"

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.16.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.otp_autofill
        pluginClass: OTPPlugin
      ios:
        pluginClass: OTPPlugin
